idade_1 = float(input(f"Pess_1 > Digite sua idade: "))
altura_1 = float(input(f"Pess_1 > Digite sua altura: "))
idade_2 = float(input(f"Pess_2 > Digite sua idade: "))
altura_2 = float(input(f"Pess_2 > Digite sua altura: "))
idade_3 = float(input(f"Pess_3 > Digite sua idade: "))
altura_3 = float(input(f"Pess_3 > Digite sua altura: "))
idade_4 = float(input(f"Pess_4 > Digite sua idade: "))
altura_4 = float(input(f"Pess_4 > Digite sua altura: "))
idade_5 = float(input(f"Pess_5 > Digite sua idade: "))
altura_5 = float(input(f"Pess_5 > Digite sua altura: "))

print(f"Pess_1: Altura:{altura_1} / Idade:{idade_1}")
print(f"Pess_2: Altura:{altura_2} / Idade:{idade_2}")
print(f"Pess_3: Altura:{altura_3} / Idade:{idade_3}")
print(f"Pess_4: Altura:{altura_4} / Idade:{idade_4}")
print(f"Pess_5: Altura:{altura_5} / Idade:{idade_5}")
